services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 192.168.92.10
  db:
    image: postgres:14.11
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 192.168.92.12
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
