services:
  backend:
    environment:
      - FASTAPITUT_POSTGRESQL_DB_HOST=db
      - FASTAPITUT_POSTGRESQL_DB_NAME=fastapitutdbprod
      - FASTAPITUT_POSTGRESQL_DB_USER=myuserprod
      - FASTAPITUT_POSTGRESQL_DB_PASS=mypassprod
    #deploy:
    #replicas: 3
    #update_config:
    #  parallelism: 2
    #  delay: 10s
    #restart_policy:
    #  condition: on-failure
  db:
    environment:
      - POSTGRES_DB=fastapitutdbprod
      - POSTGRES_USER=myuserprod
      - POSTGRES_PASSWORD=mypassprod
    volumes:
      - pgdata-prod:/var/lib/postgresql/data:rw
volumes:
  pgdata-prod:
